"""baseline: the schema as create_all last left it

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-21 02:30:04.525587+00:00

Every statement here is `IF NOT EXISTS`, which is what lets one code path serve
both kinds of database this project now has:

  * a fresh one, where this creates the whole schema, and
  * one that has been running on `Base.metadata.create_all`, where almost
    everything exists already and this fills in whatever `create_all` was
    unable to add after the fact.

That second case is why the file is hand-written PostgreSQL rather than the
autogenerated `op.create_table` calls. Stamping the legacy database instead
would have been shorter, but a stamp *asserts* that the schema matches -- and
`create_all` never adds an index to a table it did not create, so the assertion
is false on any deployment that gained an index after its table had shipped.
Filling the gaps in is checkable afterwards with `alembic check`; asserting
them away is not.

The DDL is frozen. It records the shape the models had at this revision, and
must not be edited to follow them later -- that is what further revisions are
for.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# `bigserial` rather than an identity column: this has to reproduce byte for
# byte what SQLAlchemy's `BigInteger` primary key emitted, or a fresh database
# and a migrated one would disagree about the sequence and every later
# autogenerate would report the difference forever.
_TABLES: tuple[str, ...] = (
    """
    create table if not exists app_user (
        id bigserial primary key,
        username varchar(32) not null,
        email varchar(255) not null,
        phone varchar(32),
        password_hash varchar(255) not null,
        role varchar(16) default 'USER' not null,
        is_active boolean default true not null,
        must_change_password boolean default false not null,
        created_at timestamptz default now() not null,
        updated_at timestamptz default now() not null,
        constraint ck_app_user_role check (role in ('ADMIN', 'USER'))
    )
    """,
    """
    create table if not exists refresh_token (
        token_hash varchar(64) primary key,
        user_id bigint not null references app_user (id) on delete cascade,
        expires_at timestamptz not null,
        revoked_at timestamptz,
        created_at timestamptz default now() not null
    )
    """,
    """
    create table if not exists watchlist_item (
        user_id bigint not null references app_user (id) on delete cascade,
        sid varchar(16) not null,
        "position" integer not null,
        created_at timestamptz default now() not null,
        primary key (user_id, sid)
    )
    """,
    """
    create table if not exists stock_code (
        code varchar(16) primary key,
        name varchar(64) not null,
        type varchar(32) not null,
        market varchar(16) not null,
        "group" varchar(64) not null,
        isin varchar(24) not null,
        start varchar(16) not null,
        data_source varchar(8) not null,
        is_active boolean default true not null,
        delisted_at timestamptz,
        synced_at timestamptz default now() not null
    )
    """,
    """
    create table if not exists daily_price (
        sid varchar(16) not null,
        date date not null,
        capacity bigint,
        turnover bigint,
        open numeric(12, 4),
        high numeric(12, 4),
        low numeric(12, 4),
        close numeric(12, 4),
        change numeric(12, 4),
        transaction integer,
        note varchar(64),
        updated_at timestamptz default now() not null,
        primary key (sid, date)
    )
    """,
    """
    create table if not exists fetch_log (
        sid varchar(16) not null,
        year smallint not null,
        month smallint not null,
        row_count integer not null,
        source varchar(8) not null,
        fetched_at timestamptz default now() not null,
        primary key (sid, year, month)
    )
    """,
    """
    create table if not exists dividend_event (
        sid varchar(16) not null,
        ex_date date not null,
        name varchar(64) not null,
        kind varchar(8) not null,
        close_before numeric(16, 6),
        reference_price numeric(16, 6),
        deduction numeric(16, 8),
        cash_dividend numeric(16, 8),
        stock_dividend numeric(16, 8),
        source varchar(8) not null,
        updated_at timestamptz default now() not null,
        primary key (sid, ex_date)
    )
    """,
    """
    create table if not exists dividend_fetch_log (
        source varchar(8) not null,
        bucket varchar(16) not null,
        row_count integer not null,
        fetched_at timestamptz default now() not null,
        primary key (source, bucket)
    )
    """,
    """
    create table if not exists job_schedule (
        job_id varchar(48) primary key,
        enabled boolean default true not null,
        kind varchar(16) default 'interval' not null,
        interval_minutes integer not null,
        daily_at varchar(5) not null,
        updated_at timestamptz default now() not null,
        updated_by varchar(32),
        constraint ck_job_schedule_kind check (kind in ('interval', 'daily')),
        constraint ck_job_schedule_interval check (interval_minutes > 0)
    )
    """,
    """
    create table if not exists job_run (
        id bigserial primary key,
        job_id varchar(48) not null,
        started_at timestamptz not null,
        finished_at timestamptz not null,
        status varchar(16) not null,
        trigger varchar(16) not null,
        actor varchar(32),
        stats jsonb default '{}'::jsonb not null,
        message varchar(255),
        constraint ck_job_run_status check (status in ('success', 'skipped', 'failed'))
    )
    """,
)

# Kept apart from the tables above on purpose. `create_all` gives a table every
# index the model declared *at the moment the table was created* and never
# revisits it, so an index added to an existing model is precisely what a
# long-lived database turns out to be missing.
_INDEXES: tuple[str, ...] = (
    "create unique index if not exists ux_app_user_username_lower"
    " on app_user (lower(username))",
    "create unique index if not exists ux_app_user_email_lower"
    " on app_user (lower(email))",
    "create index if not exists ix_refresh_token_user_expires"
    " on refresh_token (user_id, expires_at)",
    "create index if not exists ix_watchlist_item_user_position"
    ' on watchlist_item (user_id, "position")',
    "create index if not exists ix_stock_code_active on stock_code (is_active)",
    "create index if not exists ix_daily_price_sid_date on daily_price (sid, date)",
    "create index if not exists ix_job_run_job_started on job_run (job_id, started_at)",
)

# Formerly app/schema_patches.py, which ran on every boot because there was
# nowhere else to put a column added after its table had shipped. Folded in
# here so a database predating the column still converges, and so that file
# could be deleted rather than left behind as a second, competing mechanism.
_COLUMNS: tuple[str, ...] = (
    "alter table app_user "
    "add column if not exists must_change_password boolean not null default false",
)


def upgrade() -> None:
    for statement in (*_TABLES, *_INDEXES, *_COLUMNS):
        op.execute(statement)


def downgrade() -> None:
    # Ordered so a table goes before the one its foreign key points at.
    for table in (
        "job_run",
        "job_schedule",
        "dividend_fetch_log",
        "dividend_event",
        "fetch_log",
        "daily_price",
        "stock_code",
        "watchlist_item",
        "refresh_token",
        "app_user",
    ):
        op.execute(f"drop table if exists {table}")
